spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1034478446062-t8g2n3p6peugp65gqlknurjtk6g1hdk4.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          github:
            client-id: a8cf5060b620711b3a97
            client-secret: ab999a2c007545e5b3a45365beb583a9208ab604
          naver:
            client-id: inPe6oE1BQjiKUYwQcmV
            client-secret: w1Gqv13MVo
            scope: name, email, nickname, gender, birthday, birthyear
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: 86ead32bca13a782eecf97ea7d5aab9f
            client-secret: VUPqtpF7LjtTUkYNDdWcphZrBTLcCqkS
            scope: profile_nickname, account_email, gender, birthday
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  auth:
    cookie:
      refresh-cookie-key: "refresh"